### ISSUE TITLE
Use `hexo` in `node_modules/` instead of global one

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo-starter#3]
For example

``` json
"scripts": {
  "serve": "hexo server",
  "build": "hexo build"
}
```

Then we can reuse `./node_modules/.bin/hexo` and the user do not have to install `hexo-cli` globally (for existing Hexo site).

[How to Solve the Global npm Module Dependency Problem](http://www.sitepoint.com/solve-global-npm-module-dependency-problem/)

---

**Update (2019-07-11)**

`npx` is included in `npm` since v5.3, it will use binaries in `./node_modules/.bin`, and install command temporarily if not available in `node_modules/`.
[How to use npx: the npm package runner](https://blog.scottlogic.com/2018/04/05/npx-the-npm-package-runner.html)

Here are my latest commands:

```sh
# local serve
npx hexo clean && npx hexo server

# deploy
npx hexo clean && npx hexo generate && npx hexo deploy
```

**Comment by tomap** [comment]
We could make sure that this project already includes the command lines we need, and update 
documentation to explain the new commands:
"scripts": {
  "hexo": "hexo",
  "server": "hexo server",
  "build": "hexo build"
}

`hexo server` => `npm run server` 
And to add parameters: https://stackoverflow.com/a/14404223/383029
`hexo server -o` => `npm run server -- -o` 

I believe there are a bunch of PR/Issues here and there asking for that.
I'll try to reference them from here.
As this is a breaking change, we should first introduce the new "scripts" section in package.json, and then add a depreciation notice in the command line for all commands except init
and then only, remove old commands

**Comment by weyusi** [comment]
you could also set `PATH="$PATH:./node_modules/.bin"` in ~/.profile to use hexo without hexo-cli.

**Comment by tomap** [comment]
Super partial solution:
https://github.com/tomap/tpi2.eu/blob/master/package.json#L28

**Comment by leesei** [comment]
There is no need to add NPM scripts now that `npx` is available, see update in original post.
I think this issue can be closed after the usage is added to the docs.

**Comment by weyusi** [comment]
My suggestion:
1. Remove command from https://hexo.io/docs/#Requirements and replace with `Skip to [Hexo installation](#Install-Hexo)`.
2. Add a "Advanced users" heading to the bottom of https://hexo.io/docs/, add npx and $PATH tips there.

**Comment by weyusi** [comment]
> There is no need to add NPM scripts now that `npx` is available.
Just tested `npx hexo s -p 3001`, it works; no need `--` like npm run.

**Comment by tomap** [comment]
Ok. Great. So all we need is a PR on hexojs/site to explain the new way to use hexo cli, + a blog post to announce it.
Maybe preserve the old way in the doc temporarily?

**Comment by weyusi** [comment]
Currently, `$ npm install -g hexo-cli` is shown twice (i.e. [Requirements](https://hexo.io/docs/#Requirements) and [Install Hexo](https://hexo.io/docs/#Install-Hexo) sections) under the same page.
I think the command is still more beginner-friendly than `npx` and `$PATH`, so I suggest to retain it. This also means no breaking change, just some pro-tips™ for advanced users.
I'll also add a note `...you might need $ sudo npm install...`

**Comment by leesei** [comment]
> My suggestion:
> 
> 1. Remove command from [hexo.io/docs/#Requirements](https://hexo.io/docs/#Requirements) and replace with `Skip to [Hexo installation](#Install-Hexo)`.
> 2. Add a "Advanced users" heading to the bottom of [hexo.io/docs](https://hexo.io/docs/), add npx and $PATH tips there.

I think there are two use cases:
1. `hexo init` to initialize project (which is fulfilled by `hexo-cli`)
2. run `hexo` commands in an existing project

Actually `npx` also works for the first case since it will try to install `hexo` the if it is not found locally or globally.

**Comment by weyusi** [comment]
yeah, npx is pretty robust, `npx hexo init` works even when `node_modules/hexo` is in parent folder (current folder needs to be empty).

**Comment by curbengh** [comment]
Submitted PR https://github.com/hexojs/site/pull/1017

**Comment by curbengh** [comment]
shall we also recommend user to change global installation of npm packages from `/usr/local/bin` to `$HOME/.local/bin`?
Ubuntu already add `$HOME/.local/bin` to $PATH by default.

This way, `npm install -g` doesn't need sudo or [chown](https://github.com/hexojs/hexo/issues/2785#issuecomment-338391933).

**Comment by tomap** [comment]
@curbengh I do not understand the whole $PATH stuff.
It is not necessary on windows.

With just installing node 8+, you can run `npx hexo init` from anywhere without having to install hexo locally or globally

For this issue, I believe we can close it, can't we?

**Comment by curbengh** [comment]
Indeed, it doesn't apply to Windows.

In Linux (at least in Ubuntu), `npm install -g` would result in permission error in default installation as the default installation path is `/usr/local/bin` which requires root/sudo permission. The fix is changing the installation path.

hexo website already links to the solution provided by [npmjs.com](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). So I guess we don't need the $PATH thing.

I'll close this after I add `server` and `clean` scripts.
