### ISSUE TITLE
hexo init 卡住了

### ISSUE THREAD

**Issue by objcoding** [hexojs/hexo-starter#48]
![image](https://user-images.githubusercontent.com/24354760/101278756-a683ba80-37f8-11eb-9eca-7ff9cb974450.png)

**Comment by objcoding** [comment]
一直卡着不动（已经科学上网的情况下）

**Comment by kyriewxcode** [comment]
俺也一样

**Comment by JJJime** [comment]
这不可能是Hexo的问题吧，「hexo init」命令只是使用「git clone」从仓库下载一个内容下来，如果你要直接在当前文件夹下进行clone的话，则仅执行「hexo init」就可以了，不用加「./」，如果卡死的话，检查一下有没有用root用户（加sudo 或者先执行sudo su）

**Comment by lchr123** [comment]
虽然挂了梯子但是命令行还是没有走vpn

**Comment by stevenjoezhang** [comment]
是的，请检查命令行是否启用了代理
