### ISSUE TITLE
 TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by JunKuangKuang** [hexojs/hexo-starter#60]
Too disappointed！

I clone it and I install dependencies.

Next, I try to run `hexo clean` but it did not work. 

Four years ago, it was a good projects that anyone could run it for writting blogs. Anyone with no foundation can run it directly.

Now, an initial project that doesn't work directly discourages beginners who want to get into Hexo.

[](https://github.com/Keen-King/hexo-start2/blob/main/image-20220725230430421.png)

**Comment by stevenjoezhang** [comment]
`Object.fromEntries` is supported since Node.js 12
The error message indicates that you're using Node.js 10 or lower, which are End-of-Life
See https://github.com/nodejs/Release
